name: Hudson Design Labs
favicon: null
layout_spectrum: 0.12013877625577152
typography_spectrum: 0.44260246958583593
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.5981675097718835
  lightness: 0.2972502855118364
  saturation: 0.6554285823367536
  rhythmicContrast: 0.682637108489871
purpose: []
